package com.fsl.manager.dao;

import com.fsl.manager.pojo.Rightinfo;
import com.fsl.manager.pojo.RightinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RightinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int countByExample(RightinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int deleteByExample(RightinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int insert(Rightinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int insertSelective(Rightinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    List<Rightinfo> selectByExample(RightinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    Rightinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Rightinfo record, @Param("example") RightinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByExample(@Param("record") Rightinfo record, @Param("example") RightinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByPrimaryKeySelective(Rightinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rightinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByPrimaryKey(Rightinfo record);
}