package com.fsl.manager.dao;

import com.fsl.manager.pojo.Roleright;
import com.fsl.manager.pojo.RolerightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolerightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int countByExample(RolerightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int deleteByExample(RolerightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int insert(Roleright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int insertSelective(Roleright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    List<Roleright> selectByExample(RolerightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    Roleright selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Roleright record, @Param("example") RolerightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByExample(@Param("record") Roleright record, @Param("example") RolerightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByPrimaryKeySelective(Roleright record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleright
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByPrimaryKey(Roleright record);
}