package com.fsl.manager.dao;

import com.fsl.manager.pojo.Roleinfo;
import com.fsl.manager.pojo.RoleinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int countByExample(RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int deleteByExample(RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int insert(Roleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int insertSelective(Roleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    List<Roleinfo> selectByExample(RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    Roleinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Roleinfo record, @Param("example") RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByExample(@Param("record") Roleinfo record, @Param("example") RoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByPrimaryKeySelective(Roleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbggenerated Tue Nov 12 16:01:03 CST 2019
     */
    int updateByPrimaryKey(Roleinfo record);
}