package com.fsl.manager.pojo;

import java.io.Serializable;

public class Rightinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rightinfo.ID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rightinfo.RightName
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private String rightname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rightinfo.Description
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rightinfo.ID
     *
     * @return the value of rightinfo.ID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rightinfo.ID
     *
     * @param id the value for rightinfo.ID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rightinfo.RightName
     *
     * @return the value of rightinfo.RightName
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public String getRightname() {
        return rightname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rightinfo.RightName
     *
     * @param rightname the value for rightinfo.RightName
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setRightname(String rightname) {
        this.rightname = rightname == null ? null : rightname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rightinfo.Description
     *
     * @return the value of rightinfo.Description
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rightinfo.Description
     *
     * @param description the value for rightinfo.Description
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}