package com.fsl.manager.pojo;

import java.io.Serializable;
import java.util.Date;

public class Userinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserName
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.PWD
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.E_Mail
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private String eMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Phone
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.RegisterTime
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Description
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.ID
     *
     * @return the value of userinfo.ID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.ID
     *
     * @param id the value for userinfo.ID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserName
     *
     * @return the value of userinfo.UserName
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserName
     *
     * @param username the value for userinfo.UserName
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.PWD
     *
     * @return the value of userinfo.PWD
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.PWD
     *
     * @param pwd the value for userinfo.PWD
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.E_Mail
     *
     * @return the value of userinfo.E_Mail
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.E_Mail
     *
     * @param eMail the value for userinfo.E_Mail
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Phone
     *
     * @return the value of userinfo.Phone
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Phone
     *
     * @param phone the value for userinfo.Phone
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.RegisterTime
     *
     * @return the value of userinfo.RegisterTime
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.RegisterTime
     *
     * @param registertime the value for userinfo.RegisterTime
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Description
     *
     * @return the value of userinfo.Description
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Description
     *
     * @param description the value for userinfo.Description
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}