package com.fsl.manager.pojo;

import java.io.Serializable;

public class Userrole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.ID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.RoleInfoID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private Integer roleinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.RightInfoID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    private Integer rightinfoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.ID
     *
     * @return the value of userrole.ID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.ID
     *
     * @param id the value for userrole.ID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.RoleInfoID
     *
     * @return the value of userrole.RoleInfoID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public Integer getRoleinfoid() {
        return roleinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.RoleInfoID
     *
     * @param roleinfoid the value for userrole.RoleInfoID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setRoleinfoid(Integer roleinfoid) {
        this.roleinfoid = roleinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.RightInfoID
     *
     * @return the value of userrole.RightInfoID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public Integer getRightinfoid() {
        return rightinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.RightInfoID
     *
     * @param rightinfoid the value for userrole.RightInfoID
     *
     * @mbg.generated Tue Nov 12 15:40:11 CST 2019
     */
    public void setRightinfoid(Integer rightinfoid) {
        this.rightinfoid = rightinfoid;
    }
}